name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/rails-5.2-mongo.gemfile
      - run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.6
        ports:
          - 27017:27017
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.1'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
        gemfile:
          - gemfiles/rails-4.0-mongo.gemfile
          - gemfiles/rails-4.0-mongoid.gemfile
          - gemfiles/rails-4.1-mongo.gemfile
          - gemfiles/rails-4.1-mongoid.gemfile
          - gemfiles/rails-4.2-mongo.gemfile
          - gemfiles/rails-4.2-mongoid.gemfile
          - gemfiles/rails-5.0-mongo.gemfile
          - gemfiles/rails-5.0-mongoid.gemfile
          - gemfiles/rails-5.1-mongo.gemfile
          - gemfiles/rails-5.1-mongoid.gemfile
          - gemfiles/rails-5.2-mongo.gemfile
          - gemfiles/rails-5.2-mongoid.gemfile
          - gemfiles/rails-6.0-mongo.gemfile
          - gemfiles/rails-6.0-mongoid.gemfile
        exclude:
          # Ruby 2.1 - exclude Rails 5.0+
          - ruby: '2.1'
            gemfile: gemfiles/rails-5.0-mongo.gemfile
          - ruby: '2.1'
            gemfile: gemfiles/rails-5.0-mongoid.gemfile
          - ruby: '2.1'
            gemfile: gemfiles/rails-5.1-mongo.gemfile
          - ruby: '2.1'
            gemfile: gemfiles/rails-5.1-mongoid.gemfile
          - ruby: '2.1'
            gemfile: gemfiles/rails-5.2-mongo.gemfile
          - ruby: '2.1'
            gemfile: gemfiles/rails-5.2-mongoid.gemfile
          - ruby: '2.1'
            gemfile: gemfiles/rails-6.0-mongo.gemfile
          - ruby: '2.1'
            gemfile: gemfiles/rails-6.0-mongoid.gemfile
          # Ruby 2.3 - exclude Rails 6.0
          - ruby: '2.3'
            gemfile: gemfiles/rails-6.0-mongo.gemfile
          - ruby: '2.3'
            gemfile: gemfiles/rails-6.0-mongoid.gemfile
          # Ruby 2.4 - exclude Rails 4.0, 4.1, and 6.0
          - ruby: '2.4'
            gemfile: gemfiles/rails-4.0-mongo.gemfile
          - ruby: '2.4'
            gemfile: gemfiles/rails-4.0-mongoid.gemfile
          - ruby: '2.4'
            gemfile: gemfiles/rails-4.1-mongo.gemfile
          - ruby: '2.4'
            gemfile: gemfiles/rails-4.1-mongoid.gemfile
          - ruby: '2.4'
            gemfile: gemfiles/rails-6.0-mongo.gemfile
          - ruby: '2.4'
            gemfile: gemfiles/rails-6.0-mongoid.gemfile
          # Ruby 2.5 - exclude Rails 4.0, 4.1, 4.2
          - ruby: '2.5'
            gemfile: gemfiles/rails-4.0-mongo.gemfile
          - ruby: '2.5'
            gemfile: gemfiles/rails-4.0-mongoid.gemfile
          - ruby: '2.5'
            gemfile: gemfiles/rails-4.1-mongo.gemfile
          - ruby: '2.5'
            gemfile: gemfiles/rails-4.1-mongoid.gemfile
          - ruby: '2.5'
            gemfile: gemfiles/rails-4.2-mongo.gemfile
          - ruby: '2.5'
            gemfile: gemfiles/rails-4.2-mongoid.gemfile
          # Ruby 2.6 - exclude Rails 4.0, 4.1, 4.2
          - ruby: '2.6'
            gemfile: gemfiles/rails-4.0-mongo.gemfile
          - ruby: '2.6'
            gemfile: gemfiles/rails-4.0-mongoid.gemfile
          - ruby: '2.6'
            gemfile: gemfiles/rails-4.1-mongo.gemfile
          - ruby: '2.6'
            gemfile: gemfiles/rails-4.1-mongoid.gemfile
          - ruby: '2.6'
            gemfile: gemfiles/rails-4.2-mongo.gemfile
          - ruby: '2.6'
            gemfile: gemfiles/rails-4.2-mongoid.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      - run: bundle exec rake test
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
